[package]
name = "wmi"
version = "0.1.0"
authors = ["Ohad Ravid <ohad.rv@gmail.com>"]
edition = "2018"
license = "MIT|Apache-2.0"
readme = "README.md"
documentation = "https://ohadravid.github.io/wmi-rs/docs/wmi/"
homepage = "https://github.com/ohadravid/wmi-rs"
repository = "https://github.com/ohadravid/wmi-rs"
description = """
WMI crate for rust.
"""
categories = ["api-bindings", "os::windows-apis"]
keywords = ["wmi", "com", "win32"]

[features]
test = []

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { git = "https://github.com/retep998/winapi-rs.git", branch = "0.3", features = ["objbase", "wbemcli", "objidlbase", "oaidl", "oleauto", "errhandlingapi"] }
failure = "*"
log = "*"
env_logger = "*"
base64 = "*"
regex = "*"
lazy_static = "*"
simple_logger = "*"
widestring = "*"
serde = { version = "*", features = ["derive"] }
chrono = { version = "*", features = ["serde"] }

[dev-dependencies]
lazy_static = "1.2.0"
